---
runners:
  plugin: threaded
  options:
    num_workers: 200

inventory:
  plugin: SimpleInventory
  options:
    host_file: "../network_inventory/hosts.yaml"
    group_file: "../network_inventory/groups.yaml"
    defaults_file: "../network_inventory/defaults.yaml"
